### ISSUE TITLE
UI Automatically set shift_open when creating new shifts

### ISSUE THREAD

**Issue by ncbui** [OurTimeForTech/shiftwork2#75] opened 2021-04-29 23:21 UTC
- [ ] automatically set shift_open when creating new shifts
- [ ] remove the dropdown menu from form

**Comment by saradotlog** [comment] 2021-04-30 16:16
I also thought about this when working on the shifts, but then I thought, it might be a good thing to give the option to the orgs to create the shift as filled if they want, so no worker can take it from the beginning (for example if they want to have it there but update anything later) and then open it when they are ready? specially if filled shifts can't be updated
I think is something to discuss @ncbui @GabrielleEaston @Timilehin08

**Comment by GabrielleEaston** [comment] 2021-04-30 16:22
@saradotlog Good point! Then maybe we can leave the dropdown.

**Comment by ncbui** [comment] 2021-04-30 17:01
That would be a nice option. I'm wary of using the 'filled' option to fulfill that need since it already has so many connotations to it. Could we call this state of "Created but not available for worker sign up" something else?

**Comment by saradotlog** [comment] 2021-04-30 17:21
You are right, but I would say filled is a good option for our MVP as adding a new state would be new functionality... Can be a nice to have I think. But as always I'm open to whatever you decide 😊

**Comment by msarit** [comment] 2021-05-01 01:53
Good discussion!

Now that I think about it, there really isn't a use-case for setting a new `Shift` to `filled` upon creation.

When a shift is `filled`, the `Shift.worker_id` field is populated with the `id` of the worker who filled it.

If we allow `shifts` to be set to `filled` when they are created, how do we then populate the `shift.worker_id` field at the same time?

If we decide to implement this change, here are the tasks necessary:
- [ ] Create an issue describing the changes needed
- [ ] remove the `shift status` field from the "Create Shift" and "Edit Shift" forms
- [ ] remove the `shift_open` attribute from the `permitted` params for the `shifts#create` and `shifts#update` controller actions

@saradotlog @GabrielleEaston @ncbui @Timilehin08

**Comment by saradotlog** [comment] 2021-05-01 15:34
In my opinion it has the the use-case of giving more flexibility to organizations, as they can create the shift but leave it "in pause" for a bit if they want to re-think something so workers can't take it immediately. 

Also, if the shift is created but after a while they realise they want to change something, giving them the chance to mark it as "filled" so it is temporary unavailable to be taken it's an added feature, it is already in place, and I find it can be nice. Otherwise they would have to delete it while they think of the change to don't risk a worker take it in the meanwhile. Again, organizations are not allowed to edit the shift once is taken, so with this at least they have a bit more room for changes.

About the shift worker id I don't see it as a problem. It can be blank if the org. set it as filled, and once they open it and it is taken the worker id will get stored in the shift. Also the worker name can be blank until the shift is taken, that is something that only the organization who owns the shift can see, so for me that has an easy solution and it is not a problem. We also would need to check if the worker_id is filled, and if is not, leave the edit button available.

Of course the best solucion would be what Cam said, adding a kind of "temporarily unavailable" option in the dropdown, but I thought that could be extra work for something that again, in my opinion, is not a bug, is an optimization, and it gives extra functionality and flexibility to our app.

Buuuuut that's only my opinion! I don't think there is right or wrong, just the decision of what we want to give or not to our users! 😅 😅 😅

**Comment by GabrielleEaston** [comment] 2021-05-02 16:26
My suggestion is to go over it tomorrow during the meeting 😊

**Comment by msarit** [comment] 2021-05-06 19:38
Let's close this issue, seeing as it's not a app-breaker.

**Closed by msarit** 2021-05-06 19:38 UTC
Labels: In Planning
